apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1yv0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1yv0
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1yv0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1yv0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1yv0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lsgg-tenant/rhtap-demo-app/hacbs-test-project-1yv0@sha256:e301ce9c77c565394c4bdb50de321dcab0fd682116a4ec613e166974ded8850c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
