apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1yv0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lsgg-tenant/rhtap-demo-app/hacbs-test-project-1yv0@sha256:e301ce9c77c565394c4bdb50de321dcab0fd682116a4ec613e166974ded8850c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
